# Generated by Django 5.1.2 on 2024-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regester',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regester',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regester',
            name='gender',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
