# Generated by Django 5.1.2 on 2024-10-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0002_regester_address_regester_age_regester_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regester',
            name='image',
        ),
    ]
