# Generated by Django 5.1.2 on 2024-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0003_remove_regester_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regester',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
