# Generated by Django 5.1.2 on 2024-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0004_alter_regester_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address',
                  models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
