# Generated by Django 5.1.2 on 2024-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0005_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
