# Generated by Django 5.1.2 on 2024-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0006_alter_organizer_age_alter_organizer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(blank=True, null=True)),
                ('customernumber', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(blank=True, null=True)),
                ('eventname', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('sampleimage', models.CharField(blank=True, max_length=50, null=True)),
                ('organizerid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='regester',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
