# Generated by Django 5.1.2 on 2025-01-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0008_alter_event_sampleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sampleimage',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
