# Generated by Django 5.1.2 on 2025-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0010_review_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='fb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.CharField(choices=[('1STAR', '1star'), ('2STAR', '2star'), ('3STAR', '3star'), ('4STAR', '4star'), ('5STAR', '5star')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
