# Generated by Django 5.0.4 on 2025-01-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0011_fb_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regester',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
