# Generated by Django 5.0.4 on 2025-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0012_alter_regester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
