# Generated by Django 5.0.4 on 2025-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0013_alter_fb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sampleimage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
