# Generated by Django 5.1.2 on 2025-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0015_eventsupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
