# Generated by Django 5.1.2 on 2025-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0016_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
