# Generated by Django 5.1.2 on 2025-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlive', '0017_alter_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oreg/'),
        ),
        migrations.AddField(
            model_name='regester',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reg/'),
        ),
    ]
