# Generated by Django 5.1.3 on 2025-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventlive", "0019_cart_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsupdates",
            name="stock",
            field=models.IntegerField(default=100),
        ),
    ]
